version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.19.0 # the primary container, where your job's commands are run
      - image: circleci/mongo:4.4.10
      environment:
          - MONGODB_USERNAME: "myrootuser"
          - MONGODB_PASSWORD: "mypassword"
       # auth:
        #  username: mydockerhub-user
        #  password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: ~/11249group10
    steps:
      - checkout
      #- restore_cache:
      #    keys:
      #      - v1-dependencies-{{ checksum "frontend/package.json"}}
      #      - v1-dependencies-

      - run: npm install
      - run: npm --prefix ./backend install
      - run: npm --prefix ./frontend install
     # - run: ./node_modules/mocha/bin/mocha backend/test/

      #- save_cache:
      #    paths:
      #      - node_modules
      #    key: v1-dependencies-{{ checksum "frontend/package.json"}}
      - run: npm --prefix ./frontend run build