version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.19.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: ~/11249group10
    steps:
      - checkout
      #- restore_cache:
      #    keys:
      #      - v1-dependencies-{{ checksum "frontend/package.json"}}
      #      - v1-dependencies-

      - run: npm install --save
      - run: npm --prefix ./backend npm install --save
     # - run: ./node_modules/mocha/bin/mocha backend/test/

      #- save_cache:
      #    paths:
      #      - node_modules
      #    key: v1-dependencies-{{ checksum "frontend/package.json"}}

      - run: npm --prefix ./backend run test