version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: ~/repo
    steps:
      #- checkout # check out the code in the project directory
      #- restore_cache:
      #    keys:
      #      - v1-dependencies-{{ checksum "frontend/package.json"}}
      #      - v1-dependencies-

      - run: npm install

      #- save_cache:
      #    paths:
      #      - node_modules
      #    key: v1-dependencies-{{ checksum "frontend/package.json"}}

      - run: cd backend && npm run test